
# 开发环境配置
server:
  # 服务端口
  port: 8080

# Spring配置
spring:
  application:
    #本项目名称
    name: cm-digital-twin
  # 数据源配置
  datasource:
    name: dataSource
    type: com.zaxxer.hikari.HikariDataSource
    #driverClassName: com.mysql.jdbc.Driver
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/foot?characterEncoding=utf-8&useUnicode=true&allowLoadLocalInfile=true&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
  data:
    mongodb:
      database: digital_twins
      host: 39.107.250.91
      port: 27017
      username: zlroot
      password: zlroot
      #uri: mongodb://zlroot:zlroot@39.107.250.91:27017/admin
      authentication-database: admin


# MyBatis
mybatis:
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mapper/mybatis-config.xml
  type-aliases-package: com.chinamobile.foot.*

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  #分页参数合理化
  page-size-zero: true

#jwt配置
jwt:
  header: accessToken
  secret: cmcc123456
  expire: 10

# 配置日志logging:
config: classpath:logback-spring.xml
path: /home/logs

mat:
  local:
    path: C:\\braindcode\\arl-eegmodels\\examples
  upload:
    path: /mat/




debug: true
